version: '3.5'
services: 
    ms_user_db:
        container_name: ms_user_db
        image: "mysql:latest"
        restart: always
        security_opt:
            - seccomp:unconfined
        ports:
            - "3306:3306"
        volumes: 
            - ./ms_user_generator:/docker-entrypoint-initdb.d/
        environment: 
            MYSQL_DATABASE: ms_user_db
            MYSQL_USER: root
            MYSQL_PASSWORD: 153486
            MYSQL_ROOT_PASSWORD: 153486
            MYSQL_ROOT_HOST: '%'


    ms_user_rest_api:
        container_name: ms_user_rest_api
        image: "ms_user_rest_api"
        command: ["./wait-for-it.sh", "ms_user_db:3306", "--command", "echo 'dbready'"]
        depends_on:
            - ms_user_db
        ports:
            - "8080:8080"
networks: 
    default:
        external: true
        name: dayscool
    
        
