-- MySQL Script generated by MySQL Workbench
-- Sat Oct 24 15:55:19 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ms_user_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ms_user_db` ;

-- -----------------------------------------------------
-- Schema ms_user_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ms_user_db` ;
USE `ms_user_db` ;

-- -----------------------------------------------------
-- Table `ms_user_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ms_user_db`.`user` ;

CREATE TABLE IF NOT EXISTS `ms_user_db`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `birth_date` DATE NOT NULL,
  `career` VARCHAR(45) NULL,
  `role` VARCHAR(45) NULL,
  `name` VARCHAR(80) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `entry_time` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_user_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
