name: Compile and push

on:
  [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Build image
      run: docker build . --file Dockerfile --tag draco1006/nauth

    - name: Log into registry
      run: echo "${{ secrets.DOCKERPSSW }}" | docker login -u draco1006 --password-stdin

    - name: Push image
      run: |
          echo nauth
          echo latest
          docker push draco1006/nauth:latest
